### ISSUE TITLE
[question] Grid vertical extent

### ISSUE THREAD

**Issue by andizq** [TomHilder/wakeflow#13]
Why is the maximum vertical extent of the grid fixed to one pressure scale height (at R_out)? To date the majority of velocity kinks reported in the literature have been identified in 12CO, which is normally between 2-4H over the disc midplane, and at large radial separations. I would then suggest you to make `z_max` an optional argument too with a default value of e.g. 3H at R_out.

https://github.com/openjournals/joss-reviews/issues/4863

**Comment by TomHilder** [comment]
Yes this is a great point. The suggested feature has been implemented and documentation updated accordingly.

Previously this has not mattered for us as in practice I have only used the Cartesian and cylindrical grid types for 2D analysis, and any time we needed to care about line emission we have been interfacing with `MCFOST`, which chooses the maximum z for itself (and `wakeflow` uses the `MCFOST` grid).
